// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQNlJreW4BxtAQVILynhPVO1pqQVdjZoE',
    appId: '1:859120122536:web:1a28905caf3395601ea09d',
    messagingSenderId: '859120122536',
    projectId: 'judicial-exam-ac97d',
    authDomain: 'judicial-exam-ac97d.firebaseapp.com',
    storageBucket: 'judicial-exam-ac97d.appspot.com',
    measurementId: 'G-LXL6XKRKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYpvULt8tCRxUkhVq7siEchO7aZP2krqw',
    appId: '1:859120122536:android:3af66011a71410f01ea09d',
    messagingSenderId: '859120122536',
    projectId: 'judicial-exam-ac97d',
    storageBucket: 'judicial-exam-ac97d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7pDG071LWZMuU6bpmC2x95S2NGfOlyts',
    appId: '1:859120122536:ios:2aeb2a643992425e1ea09d',
    messagingSenderId: '859120122536',
    projectId: 'judicial-exam-ac97d',
    storageBucket: 'judicial-exam-ac97d.appspot.com',
    iosClientId: '859120122536-7qkkcpgjn77u4hgb6g3v22kmgl3fq81v.apps.googleusercontent.com',
    iosBundleId: 'com.example.judicialExams',
  );
}
